services:
  - type: web
    name: fcm-notification-portal-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 